"""Overview projection (spec §8): assembles the operator dashboard payload.

Split from ``pipeline.py`` so the read-side projection is separable from
orchestration and persistence. Pure function of already-computed engine outputs —
no engine calls, no writes.
"""

from __future__ import annotations

from datetime import datetime, timezone

from .. import reference as ref
from . import forecasting as fc_svc
from .context import EngineContext

DATASET_NOTE = (
    "Terminal capacity = real Port of Long Beach fact-sheet figures. "
    "Operational history is DEMO_AIS only when generated by the local SimPy layer; "
    "real NOAA AccessAIS imports are AIS and use the same forecasting/optimisation engines."
)
DAILY_OP_COST_USD = ref.DAILY_OP_COST_USD


def all_zone_codes() -> list[str]:
    return list(ref.ALL_ZONES)


def build_overview(ctx: EngineContext, forecasts: dict, hotspots, anomalies, optimiser_out: dict) -> dict:
    port = forecasts["Z-PORT"]; waiting = [v for v in ctx.vessels if v.status != "INBOUND"]; avg_wait = sum(v.anchored_hours for v in waiting) / len(waiting) if waiting else 0.0
    sched = fc_svc._arrival_schedule(ctx.vessels, 72); arrivals_next24 = int(sched[1:25].sum()); zones = []
    for z in all_zone_codes():
        fc = forecasts[z]; hist = ctx.history.get(z, []); trend = (fc.current["index"] - hist[-25].index) if len(hist) >= 25 else 0
        zones.append({"zone_code": z, "label": ref.ZONE_LABELS[z], "current_index": fc.current["index"], "peak_index": fc.peak["index"], "peak_hour": fc.peak["hour"], "queue_now": fc.current["queue"], "wait_now": fc.current["wait"], "yard_util_pct": fc.current["yard_util"], "trend": "rising" if trend > 2 else "falling" if trend < -2 else "flat", "level": "CRIT" if fc.peak["index"] >= 75 else "HIGH" if fc.peak["index"] >= 60 else "ELEVATED" if fc.peak["index"] >= 45 else "LOW", "berths": fc.capacity["berths"], "cranes": fc.capacity["cranes"], "recent_index": [round(h.index, 1) for h in hist[-48:]]})
    alerts = []
    for z in zones:
        if z["level"] in ("CRIT", "HIGH"): alerts.append({"severity": "crit" if z["level"] == "CRIT" else "warn", "title": f"{z['label']} congestion peak {z['peak_index']:.0f} at +{z['peak_hour']}h", "detail": f"Queue now {z['queue_now']} / {z['wait_now']:.0f}h avg wait; trend {z['trend']}.", "hour": z["peak_hour"]})
    long_waiters = sorted([v for v in ctx.vessels if v.anchored_hours >= 72], key=lambda v: -v.anchored_hours)
    if long_waiters: alerts.append({"severity": "warn", "title": f"{len(long_waiters)} vessel(s) anchored 72h+", "detail": f"Longest: {long_waiters[0].name} ({long_waiters[0].anchored_hours:.0f}h, {long_waiters[0].carrier})."})
    for a in anomalies:
        if a["is_anomaly"]: alerts.append({"severity": "warn", "title": f"Anomaly ({a['kind']}) at {a['zone_code']}", "detail": a["detail"]})
    opt = optimiser_out
    kpis = {"vessels_at_anchor": len(waiting), "vessels_inbound": len(ctx.vessels) - len(waiting), "avg_anchorage_wait": round(avg_wait, 1), "max_anchored_hours": round(max((v.anchored_hours for v in ctx.vessels), default=0)), "arrivals_next24": arrivals_next24, "port_index_now": port.current["index"], "peak_forecast_index": port.peak["index"], "peak_forecast_hour": port.peak["hour"], "moves_pending": sum(v.total_moves for v in ctx.vessels), "daily_fleet_burn_usd": len(waiting) * DAILY_OP_COST_USD, "berth_util_pct": opt["metrics"]["berth_util_pct"], "crane_util_pct": opt["metrics"]["crane_util_pct"]}
    return {"t0": ctx.t0.isoformat(), "dataset": {"source": ctx.dataset_source, "note": DATASET_NOTE}, "data_version": ctx.data_version, "weather_used": bool(getattr(port, "weather_used", False)), "confidence": float(getattr(port, "confidence", 1.0)), "kpis": kpis, "zones": zones, "alerts": alerts, "hotspots": hotspots, "anomalies": anomalies, "arrivals_timeline": [{"hour": i + 1, "count": int(sched[i + 1])} for i in range(72)], "last_updated": datetime.now(timezone.utc).isoformat()}
