/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Forecast */
        get: operations["forecast_api_forecast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/anomalies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Anomalies */
        get: operations["anomalies_api_anomalies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/optimise/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest */
        get: operations["latest_api_optimise_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/optimise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Optimise */
        post: operations["run_optimise_api_optimise_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tides
         * @description W3: tidal depth curve for every berth (read-only).
         *
         *     Serves whatever the tide pipeline last persisted — NOAA CO-OPS rows when present,
         *     else the labelled harmonic model — as depth_ft at each integer hour 0..hours per
         *     berth. A GET never fetches or writes: the write side lives at startup (main.py)
         *     and POST /api/tides/refresh.
         */
        get: operations["get_tides_api_tides_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tides/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Tides
         * @description Force a fresh NOAA CO-OPS fetch and replace tidal window rows.
         *
         *     Returns {source, rows_written, station} — callable from the QualityPage refresh button.
         */
        post: operations["refresh_tides_api_tides_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scenario */
        post: operations["scenario_api_scenarios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/extended": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scenario Extended
         * @description W3 extended what-if: forecast and optimise the modified context, then compare.
         */
        post: operations["scenario_extended_api_scenarios_extended_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/{scenario_id}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scenario Rollback */
        post: operations["scenario_rollback_api_scenarios__scenario_id__rollback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Routing */
        get: operations["routing_api_routing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Plan
         * @description Return the latest persisted plan or build a fresh engine-grounded plan.
         */
        get: operations["get_plan_api_plan_get"];
        put?: never;
        /** Regenerate */
        post: operations["regenerate_api_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export */
        get: operations["export_api_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/terminals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Terminals */
        get: operations["terminals_api_terminals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vessels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vessels */
        get: operations["vessels_api_vessels_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hotspots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hotspots */
        get: operations["hotspots_api_hotspots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/terminals/{code}/config_version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Bump Config Version
         * @description Module A: increment config_version so context fingerprint changes and caches invalidate.
         */
        patch: operations["bump_config_version_api_terminals__code__config_version_patch"];
        trace?: never;
    };
    "/api/vessels/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Schedule
         * @description Import a physically complete vessel schedule and immediately rebuild the plan.
         *
         *     Physical fields are mandatory. The endpoint never substitutes fabricated vessel
         *     dimensions, draft, moves or destination values.
         */
        post: operations["upload_schedule_api_vessels_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quality/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Quality Refresh
         * @description Explicit normalisation + completeness recompute (the write side of Module D).
         */
        post: operations["quality_refresh_api_quality_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Quality
         * @description Read the last computed per-terminal data-completeness snapshot (Module D).
         *
         *     Read-only by design (spec: GETs must be idempotent; B-5): normalisation runs
         *     explicitly at startup or via POST /api/quality/refresh, never on this path.
         */
        get: operations["quality_api_quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weather/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Weather Refresh
         * @description Run the W1 Open-Meteo pipeline and persist `WeatherObservation` rows.
         *
         *     Audit B-6: the pipeline existed but was never invoked, so `FEATURE_WEATHER` was
         *     unreachable and `weather_used` stayed false forever. This is the missing wiring.
         *     If Open-Meteo is unreachable the pipeline inserts nothing and this returns an
         *     empty series — the forecast then reports `weather_used: false` instead of failing.
         */
        post: operations["weather_refresh_api_weather_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weather": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Weather
         * @description Wind/wave/visibility series for San Pedro Bay (rows persisted by the pipeline).
         */
        get: operations["weather_api_weather_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bts/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bts Parse
         * @description Audit B-7: wire the BTS PPFSP benchmark parser to an endpoint (was dead code).
         *
         *     Accepts a BTS weekly-berthing CSV, validates and parses it, returning the rows
         *     for forecast validation. Keeps the benchmark load-bearing.
         */
        post: operations["bts_parse_api_bts_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ais/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ais Status */
        get: operations["ais_status_api_ais_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ais/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ais Import
         * @description Import a real NOAA AccessAIS CSV, aggregate it, and retain filtered track points.
         */
        post: operations["ais_import_api_ais_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ais/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ais Generate
         * @description Generate synthetic DEMO_AIS data for an offline/reproducible demo.
         */
        post: operations["ais_generate_api_ais_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bob/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_bob_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bob": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_api_bob_get"];
        put?: never;
        /** Ask */
        post: operations["ask_api_bob_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AisGenerateResponse
         * @description Keys = build stats + import stats + generator params (all declared).
         */
        AisGenerateResponse: {
            /** Status */
            status: string;
            /** Source */
            source: string;
            /** Message */
            message: string;
            /** Rows Scanned */
            rows_scanned: number;
            /** Skipped */
            skipped: number;
            /** Vessels */
            vessels: number;
            /** Hours */
            hours: number;
            /** Output Rows */
            output_rows: number;
            /** Inserted */
            inserted: number;
            /** Is Measured */
            is_measured: boolean;
            /** Zones */
            zones: number;
            /** Newest Ts */
            newest_ts: string;
            /** Days */
            days: number;
            /** Seed */
            seed: number;
            /**
             * Stub
             * @default false
             */
            stub: boolean;
        };
        /** AisStatusResponse */
        AisStatusResponse: {
            /** Source */
            source: string;
            /** Rows */
            rows: number;
            /** Zones */
            zones: number;
            /** Track Points */
            track_points: number;
            /** Newest Ts */
            newest_ts?: string | null;
            /** Oldest Ts */
            oldest_ts?: string | null;
            /**
             * Stub
             * @default false
             */
            stub: boolean;
        };
        /** Alert */
        Alert: {
            /** Severity */
            severity: string;
            /** Title */
            title: string;
            /** Detail */
            detail: string;
            /** Hour */
            hour?: number | null;
        };
        /** AnomaliesResponse */
        AnomaliesResponse: {
            /** Anomalies */
            anomalies: components["schemas"]["AnomalyFlag"][];
            /** Method */
            method: string;
            /** Generated At */
            generated_at: string;
            /** Weather Used */
            weather_used: boolean;
        };
        /** AnomalyFlag */
        AnomalyFlag: {
            /** Zone Code */
            zone_code: string;
            /** Kind */
            kind: string;
            /** Method */
            method: string;
            /** Score */
            score: number;
            /** Is Anomaly */
            is_anomaly: boolean;
            /** Sample Size */
            sample_size: number;
            /** Detail */
            detail: string;
            /** Confidence */
            confidence: number;
            /** Window Hours */
            window_hours: number;
            /** Features */
            features?: {
                [key: string]: unknown;
            } | null;
            /** Weather Used */
            weather_used?: boolean | null;
        };
        /** Arrival */
        Arrival: {
            /** Hour */
            hour: number;
            /** Count */
            count: number;
        };
        /** BobAnswerResponse */
        BobAnswerResponse: {
            /** Content */
            content: string;
            /** Actions */
            actions: unknown[];
            /** Mode */
            mode: string;
            /** Provider */
            provider: string;
            /** Intent */
            intent: string;
            /**
             * Grounded
             * @default true
             */
            grounded: boolean;
        };
        /** BobBody */
        BobBody: {
            /** Message */
            message: string;
        };
        /** BobHistoryResponse */
        BobHistoryResponse: {
            /** Messages */
            messages: {
                [key: string]: unknown;
            }[];
        };
        /** BobStatusResponse */
        BobStatusResponse: {
            /** Provider */
            provider: string;
            /** Configured */
            configured: boolean;
            /** Cli Available */
            cli_available: boolean;
            /** Mcp */
            mcp: string;
            /** Tools */
            tools: number;
            /** Fallback */
            fallback: string;
        };
        /** Body_ais_import_api_ais_import_post */
        Body_ais_import_api_ais_import_post: {
            /** File */
            file: string;
        };
        /** Body_bts_parse_api_bts_parse_post */
        Body_bts_parse_api_bts_parse_post: {
            /** File */
            file: string;
        };
        /** Body_upload_schedule_api_vessels_upload_post */
        Body_upload_schedule_api_vessels_upload_post: {
            /** File */
            file: string;
        };
        /** Dataset */
        Dataset: {
            /** Source */
            source: string;
            /** Note */
            note: string;
        };
        /**
         * ExtendedScenarioBody
         * @description W3: berth add/remove, crane outage, vessel bunching, schedule change.
         */
        ExtendedScenarioBody: {
            /**
             * Kind
             * @description CRANE_OUTAGE | PRODUCTIVITY | BERTH_REMOVED | BERTH_ADDED | BUNCHING | SCHEDULE_CHANGE
             * @default CRANE_OUTAGE
             */
            kind: string;
            /**
             * Crane Factor
             * @default 1
             */
            crane_factor: number;
            /**
             * Move Rate Per Crane Hour
             * @default 28
             */
            move_rate_per_crane_hour: number;
            /** Terminal Code */
            terminal_code?: string | null;
            /**
             * Berth Count Delta
             * @default 0
             */
            berth_count_delta: number;
            /**
             * Bunching Vessels
             * @default 0
             */
            bunching_vessels: number;
            /**
             * Schedule Shift Hours
             * @default -6
             */
            schedule_shift_hours: number;
            /** Parent Scenario Id */
            parent_scenario_id?: number | null;
        };
        /** ForecastResponse */
        ForecastResponse: {
            /** T0 */
            t0: string;
            /** Dataset Source */
            dataset_source: string;
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
            /** Selected */
            selected: {
                [key: string]: unknown;
            };
            hotspots: components["schemas"]["Hotspots"];
            /** Anomalies */
            anomalies: {
                [key: string]: unknown;
            }[];
            /** Weather Used */
            weather_used: boolean;
            /** Confidence */
            confidence: number;
            /** Confidence By Horizon */
            confidence_by_horizon: {
                [key: string]: unknown;
            };
            /** Horizons */
            horizons: {
                [key: string]: unknown;
            };
            /** Provenance */
            provenance: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** Hotspot */
        Hotspot: {
            /** Zone Code */
            zone_code: string;
            /** Zone Name */
            zone_name: string;
            /** Risk Score */
            risk_score: number;
            /** Confidence */
            confidence: number;
            /** Peak Index */
            peak_index: number;
            /** Peak Hour */
            peak_hour: number;
            /** Binding Constraint */
            binding_constraint: string;
            /** Binding Evidence */
            binding_evidence: {
                [key: string]: unknown;
            };
            /** Resource Pressure */
            resource_pressure: {
                [key: string]: unknown;
            };
            /** Explanation */
            explanation: string;
            /** Components */
            components: {
                [key: string]: unknown;
            };
            /** Weights */
            weights: {
                [key: string]: unknown;
            };
        };
        /** Hotspots */
        Hotspots: {
            /** Ranked */
            ranked: components["schemas"]["Hotspot"][];
            most_actionable?: components["schemas"]["Hotspot"] | null;
            /** Method */
            method?: string | null;
        };
        /** Kpis */
        Kpis: {
            /** Port Index Now */
            port_index_now: number;
            /** Berth Util Pct */
            berth_util_pct: number;
            /** Crane Util Pct */
            crane_util_pct: number;
            /** Vessels At Anchor */
            vessels_at_anchor: number;
            /** Vessels Inbound */
            vessels_inbound: number;
            /** Avg Anchorage Wait */
            avg_anchorage_wait: number;
            /** Max Anchored Hours */
            max_anchored_hours: number;
            /** Arrivals Next24 */
            arrivals_next24: number;
            /** Moves Pending */
            moves_pending: number;
            /** Daily Fleet Burn Usd */
            daily_fleet_burn_usd: number;
            /** Peak Forecast Index */
            peak_forecast_index: number;
            /** Peak Forecast Hour */
            peak_forecast_hour: number;
        };
        /** OptimiseLatest */
        OptimiseLatest: {
            /** Run Id */
            run_id?: number | null;
            /** Solver */
            solver: string;
            /** Status */
            status: string;
            /** Objective */
            objective?: number | null;
            /** Solve Ms */
            solve_ms: number;
            /** Assignments */
            assignments: {
                [key: string]: unknown;
            }[];
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
            /** Baseline */
            baseline: {
                [key: string]: unknown;
            };
            /** Deltas */
            deltas: {
                [key: string]: unknown;
            };
            /** Deferred */
            deferred: {
                [key: string]: unknown;
            }[];
            /** Weights */
            weights: {
                [key: string]: unknown;
            };
            /**
             * Tidal Feasible
             * @default true
             */
            tidal_feasible: boolean;
            /**
             * Incremental
             * @default false
             */
            incremental: boolean;
            /** Gap Pct */
            gap_pct?: number | null;
            /** Horizon Hours */
            horizon_hours?: number | null;
            /** Params */
            params?: {
                [key: string]: unknown;
            } | null;
        };
        /** Overview */
        Overview: {
            /** T0 */
            t0: string;
            dataset: components["schemas"]["Dataset"];
            /** Data Version */
            data_version: string;
            /** Weather Used */
            weather_used: boolean;
            /** Confidence */
            confidence: number;
            kpis: components["schemas"]["Kpis"];
            /** Zones */
            zones: components["schemas"]["Zone"][];
            /** Alerts */
            alerts: components["schemas"]["Alert"][];
            hotspots: components["schemas"]["Hotspots"];
            /** Anomalies */
            anomalies: {
                [key: string]: unknown;
            }[];
            /** Arrivals Timeline */
            arrivals_timeline: components["schemas"]["Arrival"][];
            /** Last Updated */
            last_updated: string;
        };
        /**
         * PlanResponse
         * @description Spec §6 traceability: the plan exposes the snapshot that produced it.
         */
        PlanResponse: {
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
            /** Shifts */
            shifts: {
                [key: string]: unknown;
            }[];
            /** Text */
            text: string;
            /** Narrative Source */
            narrative_source: string;
            /** Plan Id */
            plan_id?: number | null;
            /** Created At */
            created_at?: string | null;
            /** Forecast Run Id */
            forecast_run_id?: number | null;
            /** Optimiser Run Id */
            optimiser_run_id?: number | null;
        };
        /**
         * QualityResponse
         * @description Read-only snapshot (B-5): normalisation writes live at startup + POST /quality/refresh.
         */
        QualityResponse: {
            /** Terminals */
            terminals: {
                [key: string]: unknown;
            }[];
            /** Rules Version */
            rules_version: string;
            /** Last Run At */
            last_run_at?: string | null;
            /**
             * Stub
             * @default false
             */
            stub: boolean;
        };
        /** RoutingResponse */
        RoutingResponse: {
            /** Recommendations */
            recommendations: {
                [key: string]: unknown;
            }[];
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Total Savings Usd */
            total_savings_usd: number;
            /** Cost Model */
            cost_model: {
                [key: string]: unknown;
            };
        };
        /** ScenarioExtendedResponse */
        ScenarioExtendedResponse: {
            /** Baseline */
            baseline: {
                [key: string]: unknown;
            };
            /** Scenario */
            scenario: {
                [key: string]: unknown;
            };
            /** Impact */
            impact: {
                [key: string]: unknown;
            };
            /** Feasible */
            feasible: boolean;
            /** Kind */
            kind: string;
            /** Parent Scenario Id */
            parent_scenario_id?: number | null;
            /** Scenario Id */
            scenario_id: number;
            /** Description */
            description: string;
            /** Forecast */
            forecast: {
                [key: string]: unknown;
            };
            /** Solver */
            solver: {
                [key: string]: unknown;
            };
            /** Weights */
            weights: {
                [key: string]: unknown;
            };
        };
        /** ScenarioResponse */
        ScenarioResponse: {
            /** Scenario Id */
            scenario_id: number;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /** Baseline */
            baseline: {
                [key: string]: unknown;
            };
            /** Scenario */
            scenario: {
                [key: string]: unknown;
            };
            /** Impact */
            impact: {
                [key: string]: unknown;
            };
            /** Weights */
            weights: {
                [key: string]: unknown;
            };
            /** Solver */
            solver: {
                [key: string]: unknown;
            };
        };
        /** ScenarioRollbackResponse */
        ScenarioRollbackResponse: {
            /** Restored */
            restored: boolean;
            /** Scenario Id */
            scenario_id: number;
            /** Status */
            status: string;
        };
        /** TerminalsResponse */
        TerminalsResponse: {
            /** Terminals */
            terminals: {
                [key: string]: unknown;
            }[];
            /** Source */
            source: string;
        };
        /** TidesResponse */
        TidesResponse: {
            /** Period Hours */
            period_hours: number;
            /** Amplitude Ft */
            amplitude_ft: number;
            /** Under Keel Margin Ft */
            under_keel_margin_ft: number;
            /** Source */
            source: string;
            /** Berths */
            berths: {
                [key: string]: unknown;
            }[];
        };
        /**
         * UploadResponse
         * @description Both upload paths: the parse-failure path omits normalised_rows/replan.
         */
        UploadResponse: {
            /** Accepted */
            accepted: number;
            /** Rejected */
            rejected: number;
            /** Errors */
            errors: string[];
            /** Revisions Created */
            revisions_created: number;
            /** Normalised Rows */
            normalised_rows?: number | null;
            /** Upload Id */
            upload_id?: number | null;
            /** Filename */
            filename?: string | null;
            /** Bytes */
            bytes?: number | null;
            /**
             * Stub
             * @default false
             */
            stub: boolean;
            /** Replan */
            replan?: {
                [key: string]: unknown;
            } | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VesselsResponse */
        VesselsResponse: {
            /** Vessels */
            vessels: {
                [key: string]: unknown;
            }[];
        };
        /** WeatherResponse */
        WeatherResponse: {
            /** Points */
            points: {
                [key: string]: unknown;
            }[];
            /** Source */
            source: string;
            /** Hours */
            hours: number;
            /**
             * Stub
             * @default false
             */
            stub: boolean;
        };
        /** Zone */
        Zone: {
            /** Zone Code */
            zone_code: string;
            /** Label */
            label: string;
            /** Level */
            level: string;
            /** Trend */
            trend: string;
            /** Current Index */
            current_index: number;
            /** Peak Index */
            peak_index: number;
            /** Peak Hour */
            peak_hour: number;
            /** Recent Index */
            recent_index: number[];
            /** Queue Now */
            queue_now: number;
            /** Wait Now */
            wait_now: number;
            /** Berths */
            berths: number;
            /** Cranes */
            cranes: number;
            /** Yard Util Pct */
            yard_util_pct: number;
        };
        /** ScenarioBody */
        app__routers__optimise__ScenarioBody: {
            /**
             * Crane Factor
             * @description crane availability multiplier
             * @default 1
             */
            crane_factor: number;
            /**
             * Move Rate Per Crane Hour
             * @default 28
             */
            move_rate_per_crane_hour: number;
            /**
             * Incremental
             * @description warm-start from the previous CP-SAT solution (W3)
             */
            incremental?: boolean | null;
            /**
             * Tidal
             * @description enforce tidal windows on deep-draft vessels (W3)
             */
            tidal?: boolean | null;
        };
        /** ScenarioBody */
        app__routers__scenarios__ScenarioBody: {
            /**
             * Crane Factor
             * @default 1
             */
            crane_factor: number;
            /**
             * Move Rate Per Crane Hour
             * @default 28
             */
            move_rate_per_crane_hour: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    overview_api_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
        };
    };
    forecast_api_forecast_get: {
        parameters: {
            query?: {
                zone?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    anomalies_api_anomalies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnomaliesResponse"];
                };
            };
        };
    };
    latest_api_optimise_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimiseLatest"];
                };
            };
        };
    };
    run_optimise_api_optimise_post: {
        parameters: {
            query?: {
                /** @description alias for body.incremental (W3) */
                incremental?: boolean | null;
                /** @description alias for body.tidal (W3) */
                tidal?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["app__routers__optimise__ScenarioBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimiseLatest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tides_api_tides_get: {
        parameters: {
            query?: {
                hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TidesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_tides_api_tides_refresh_post: {
        parameters: {
            query?: {
                hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scenario_api_scenarios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["app__routers__scenarios__ScenarioBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scenario_extended_api_scenarios_extended_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtendedScenarioBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioExtendedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scenario_rollback_api_scenarios__scenario_id__rollback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioRollbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    routing_api_routing_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutingResponse"];
                };
            };
        };
    };
    get_plan_api_plan_get: {
        parameters: {
            query?: {
                text?: number;
                persist?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_api_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    export_api_export_get: {
        parameters: {
            query?: {
                type?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    terminals_api_terminals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TerminalsResponse"];
                };
            };
        };
    };
    vessels_api_vessels_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VesselsResponse"];
                };
            };
        };
    };
    hotspots_api_hotspots_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Hotspots"];
                };
            };
        };
    };
    bump_config_version_api_terminals__code__config_version_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_schedule_api_vessels_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_schedule_api_vessels_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quality_refresh_api_quality_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    quality_api_quality_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualityResponse"];
                };
            };
        };
    };
    weather_refresh_api_weather_refresh_post: {
        parameters: {
            query?: {
                hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    weather_api_weather_get: {
        parameters: {
            query?: {
                hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeatherResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bts_parse_api_bts_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_bts_parse_api_bts_parse_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ais_status_api_ais_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AisStatusResponse"];
                };
            };
        };
    };
    ais_import_api_ais_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ais_import_api_ais_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ais_generate_api_ais_generate_post: {
        parameters: {
            query?: {
                days?: number;
                seed?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AisGenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_bob_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BobStatusResponse"];
                };
            };
        };
    };
    history_api_bob_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BobHistoryResponse"];
                };
            };
        };
    };
    ask_api_bob_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BobBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BobAnswerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
